[package]
name = "codchi"
version = "0.2.0"
edition = "2021"
# Keep this in sync with NixOS stable
rust-version = "1.70.0"
build = "build.rs"

[dependencies]
clap = { version = "4", features = ["derive", "cargo"] }
clap-verbosity-flag = "2.1.0"

lazy_static = "1.4.0"
once_cell = "1.19.0"
shadow-rs = { version = "0.24" }

anyhow = { version = "1.0", features = ["backtrace"] }
thiserror = "1.0"
env_logger = "0.10"
log = "0.4"
human-panic = "1.2.2"
config = "0.13.4"

directories = "5.0.1"
# single-instance = "0.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35", features = [ "io-util", "rt-multi-thread" ] }
# tokio-util = { version = "0.7.10", features = ["codec"] }
# tokio-serde = { version = "0.8.0", features = ["messagepack"] }
parity-tokio-ipc = "0.9.0"
futures = "0.3"
futures-io = { version = "0.3" }
tarpc = { version = "0.33", features = [ "serde1", "tokio1", "serde-transport", "serde-transport-bincode" ] }

tray-icon = "0.11.1"
image = "0.24.7"
tao = "0.24.0"

[target.'cfg(unix)'.dependencies]
daemonize = "0.5.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.52", features = [ "Win32_System_Threading" ]}

[build-dependencies]
clap = { version = "4", features = ["derive", "cargo"] }
clap-verbosity-flag = "2.1.0"
clap_complete = "4.4.4"
clap_mangen = "0.2.15"
shadow-rs = { version = "0.24" }
once_cell = "1.19.0"
