[workspace]
resolver = "2"
members = [ 
    "cli", 
    # "ui", 
]

[workspace.package]
version = "0.2.0"
edition = "2021"
# Keep this in sync with NixOS stable
rust-version = "1.70.0"

[profile.release]
lto = true
strip = true

