[package]
name = "codchi"
version = "0.2.0"
edition = "2021"
# Keep this in sync with NixOS stable
rust-version = "1.70.0"
build = "build.rs"

[profile.release]
lto = true
strip = true

[dependencies]
clap = { version = "4", features = ["derive", "cargo", "string"] }
clap-verbosity-flag = "2.1.0"
once_cell = "1.19.0"
strum = { version = "0.25.0", features = ["derive"] }
itertools = "0.12.0"

anyhow = { version = "1.0", features = ["backtrace"] }
thiserror = "1.0"
env_logger = "0.10"
log = "0.4"
human-panic = "1.2.2"
comfy-table = "7.1.0"
colored = "2.1.0"

directories = "5.0.1"
# which = "5.0.0"
fs4 = { version = "0.7", features = ["sync"] }
rustls-native-certs = "0.7.0"
base64 = "0.21.7"

# config = "0.13.4"
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.4.0"
serde_json = "1.0"
toml_edit = { version = "0.21.0", features = ["serde"] }
# url = "2.5.0"
git-url-parse = "0.4.4"
lazy-regex = "3.1.0"

tokio = { version = "1.35", features = [ "io-util", "rt-multi-thread" ] }
futures = "0.3"
# futures-io = { version = "0.3" }

parity-tokio-ipc = "0.9.0"
tarpc = { version = "0.34", git = "https://github.com/google/tarpc", features = [ "serde1", "tokio1", "serde-transport", "serde-transport-bincode" ] }

tray-icon = { version = "0.11.1", default-features = false }
image = { version = "0.24", features = ["png"], default-features = false }
tao = {version = "0.24.0", default-features = false }
inquire = "0.6.2"
spinoff = { version = "0.8.0", features = ["dots"] }
dashmap = { version = "5.5.3", features = ["serde"] }

[target.'cfg(unix)'.dependencies]
daemonize = "0.5.0"

# [target.'cfg(target_os = "linux")'.dependencies]
# lxd = "0.1.9"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.52", features = [ "Win32_System_Threading" ]}
wslapi = "0.1.3"
# colored = "2.1.0"

[build-dependencies]
clap = { version = "4", features = ["derive", "cargo", "string"] }
clap-verbosity-flag = "2.1.0"
clap_complete = "4.4.4"
clap_mangen = "0.2.15"
build-data = "0"
once_cell = "1.19.0"
url = "2.5.0"
git-url-parse = "0.4.4"
lazy-regex = "3.1.0"
