[package]
name = "codchiw"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
windows = { version = "0.58.0", features = ["Win32_Foundation", "Win32_System_Console", "Win32_System_Threading", "Win32_UI_WindowsAndMessaging"] }
