name: nix

on:
  push: {}

permissions:
  contents: read

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: nixos-devenv
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#checks.x86_64-linux.populate-cache
