name: website

on:
  push:
     branches:
      - 'master'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v12
      with:
        name: nixos-devenv
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/result/
