name: website

on:
  push:
    tags:
      - "v*.*.*"
    paths:
      - docs/**
      - nix/nixos/**
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v12
      with:
        name: codchi
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake update
    - run: nix build -L
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/result/
